### ISSUE TITLE
进不去了.哭.JPG

### ISSUE THREAD

**Issue by qimeng521** [orivee/qiandao#2]
An unexpected error occurred: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
2024-08-24 12:11:05,639 - __main__ - ERROR - Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

**Comment by orivee** [comment]
可能是没有从发布页地址中解析到搜书吧的实际地址。

排查一下：
1. `SOUSHUBA_HOSTNAME` 设置的是什么？应该填写搜书吧的发布页地址，不用加 `http://` 或者 `https://`。
2. 网络问题，多试几次，或者配置代理试试

**Comment by zylf00** [comment]
> 可能是没有从发布页地址中解析到搜书吧的实际地址。
> 
> 排查一下：
> 
> 1. `SOUSHUBA_HOSTNAME` 设置的是什么？应该填写搜书吧的发布页地址，不用加 `http://` 或者 `https://`。
> 2. 网络问题，多试几次，或者配置代理试试

是变量没有生效，不知道为什么，添加Environments的时候会先让设置一个名称，不知道设置成什么。
我随便设置了一个，里面就可以添加变量了，但是里面添加的变量不生效，会出现楼主这种情况，我检查了一下，是变量没有生效。
之后我尝试不用fork，直接复制成自己的仓库，果然，添加Environments不用设置外面那个名称，直接可以添加，能生效。不知道为什么
![微信截图_20240903181254](https://github.com/user-attachments/assets/3006d07c-81b5-47a1-8d34-5ef0a01f14e8)
![微信截图_20240903181335](https://github.com/user-attachments/assets/18694e4d-0561-4c7e-8eef-98a09e890988)

**Comment by zylf00** [comment]
解决办法就是soushuba.yml文件加入这一行environment: production，然后第一个名称设置成：production
![image](https://github.com/user-attachments/assets/f784dd63-539d-4f2d-bd37-b2d44b7f9735)

**Comment by orivee** [comment]
Actions 使用的环境变量在 Secrets and variables 中设置，不是在 Environments 设置环境变量。

![Screenshot_20240912_093614-2](https://github.com/user-attachments/assets/0c5b0b90-7800-4b10-a02a-978c53567d2f)

**Comment by qimeng521** [comment]
OK，谢谢，晚上我改一下



---- 回复的原邮件 ----
| 发件人 | Sinner ***@***.***> |
| 日期 | 2024年09月12日 09:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [orivee/qiandao] 进不去了.哭.JPG (Issue #2) |

Actions 使用的环境变量在 Actions secrets 中设置，不是在 Environments 设置环境变量。

Screenshot_20240912_093614-2.png (view on web)

**Comment by orivee** [comment]
不可客气。Environments 用于部署，免费账户仅可以在公共仓库中使用。 Environments 有包含保护规则，估计你设置的变量仅用于 production 环境。

参考：https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-deployments/managing-environments-for-deployment

**Comment by zylf00** [comment]
> Actions 使用的环境变量在 Secrets and variables 中设置，不是在 Environments 设置环境变量。
> 
> ![Screenshot_20240912_093614-2](https://private-user-images.githubusercontent.com/6487389/366689235-0c5b0b90-7800-4b10-a02a-978c53567d2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjY5NzksIm5iZiI6MTcyNjEyNjY3OSwicGF0aCI6Ii82NDg3Mzg5LzM2NjY4OTIzNS0wYzViMGI5MC03ODAwLTRiMTAtYTAyYS05NzhjNTM1NjdkMmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMDczNzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTljMGM2MjM3MDVhYWMyMTY4ZDExNzZmNzE1MmM2NzliMWFkNWIyYTUzMmM3YWNiMjRlZjM4NTYzNDIwNmRlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Mql3T5vVRq9QVeb-nsGdvyhZKVj_KxpmQZgj_MsRG9c)

不是的大佬，现在fork的仓库，从Secrets and variables点进去添加变量会自动跳转到Environments，不能直接添加，自己创建的仓库才可以。不知道是不是设置的问题

**Comment by orivee** [comment]
我试了以前 fork 的仓库，是可以新建 repository secrets。试试删除仓库重新 fork 一下看看呢。

选择下面的 New repository secrets，不是上面的 Manage environment secrets。

![Screenshot_20240912_171805](https://github.com/user-attachments/assets/0ec6fe9b-122f-4580-95e9-f64089eb4e5d)

**Comment by zylf00** [comment]
> 我试了以前 fork 的仓库，是可以新建 repository secrets。试试删除仓库重新 fork 一下看看呢。
> 
> 选择下面的 New repository secrets，不是上面的 Manage environment secrets。
> 
> ![Screenshot_20240912_171805](https://private-user-images.githubusercontent.com/6487389/366806778-0ec6fe9b-122f-4580-95e9-f64089eb4e5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzQwOTYsIm5iZiI6MTcyNjEzMzc5NiwicGF0aCI6Ii82NDg3Mzg5LzM2NjgwNjc3OC0wZWM2ZmU5Yi0xMjJmLTQ1ODAtOTVlOS1mNjQwODllYjRlNWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMDkzNjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmM5NWM1OWU5MzM4NTJlYmRjZTJhZmUwNWY0NmQxNjIzNjhjZjRlYjBlMGUwNzRmZGQ5MTEyM2MyOTAxMjZjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3tzg8l5XJML8IeSJACvrHri9laIw_vhzi-Ac1IoH0is)

懂了，谢谢大佬
